---
title: "Unequal Treatment Resulting from Data:"
format: pdf
editor: Lin Dai
---

I think we should be suspicious when we find ourselves attracted to data---very, very thin and weak data---that seem to justify beliefs that have held great currency in lots of societies throughout history, in a way that is conducive to the oppression of large segments of the population.

Amia Srinivasan (Cowen 2021)

There are many unfair things cause of less data to make the conclusion. After 2000 because of many research and computer, human final can make a conclusion about that the less data can not make the right conclusion. We should always be suspicious when we find a conclusion that come from the less data.

But in the last century, they don't have computer to help them to analyze the data. That is the reason cause many unfair things happened. First, I want to talk about the Racial Discrimination and Slavery. People think the black is not a good skin human, they are not have same right with the white. How can people make that conclusion? Because of in that years there is not such that much black in the American. The few black are come from Africa by the boat to American. They are not rich, or we can say there are so poor. If not, who want to go aboard with that high risk. When the white see them might feel they are good on the working but not good on IQ. There only reason between the IQ is not the skin, it is because of the economic of the country. In that time, American have better education than the African. American people is worry about how to get higher education about the children. But the African is worry about how to get the food and get away of illness. We can make a good analyze about this is because of we got computer and many data research. But in that time, they don't have many data to conclude that. This is the unfair things between the history. Also it tells us we can not make a conclusion without huge data support you.

Second, I want to talk about the things happened after 2000. In the AI century, everybody is using the computer and phone to make their life esaier. But there also many unequal treatment happened on the internet. The basic of the internet is the bias, different application on the computer and phone got different bias.For example, in recruitment, credit, or the legal system, algorithms may reflect and amplify historical inequalities. The are many news mention about that the iPhone user got the different price on online shopping with the Android user. In the economic we called that price discrimination. This is also a kind of unequal treatment, can we using less data shows that the iPhone user is more rich than the Anroid user? Nope, we can't.

After all, We can know that use the less data to make a conclusion is not right. The result of the conclusion will affect the unequal treatment. Many people will suffer of it. 


